# Datenstrom Yellow extension settings

Extension: Pfadi
Version: 0.11.2
Description: Pfadi is a theme for scout group websites in the PPÖ design.
Designer: Liam Perlaki
Tag: theme
DownloadUrl: https://github.com/pfadfinder26/yellow-pfadi/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-pfadi
DocumentationLanguage: en, de
Published: 2026-09-29 08:19:21
Status: experimental
system/workers/pfadi.php: pfadi.php, create, update
system/layouts/pfadi-default.html: pfadi-default.html, create, update, careful
system/layouts/pfadi-banner.html: pfadi-banner.html, create, update, careful
system/layouts/pfadi-header.html: pfadi-header.html, create, update, careful
system/layouts/pfadi-navigation.html: pfadi-navigation.html, create, update, careful
system/layouts/pfadi-stufe-button.html: pfadi-stufe-button.html, create, update, careful
system/layouts/pfadi-footer.html: pfadi-footer.html, create, update, careful
system/themes/pfadi.css: pfadi.css, create, update, careful
system/themes/pfadi.js: pfadi.js, create, update, careful
system/themes/pfadi.png: pfadi.png, create
system/themes/pfadi-lilie.png: pfadi-lilie.png, create
system/themes/pfadi-halstuch.svg: pfadi-halstuch.svg, create, update, careful
system/themes/pfadi-instagram.svg: pfadi-instagram.svg, create, update, careful
system/themes/pfadi-mail.svg: pfadi-mail.svg, create, update, careful
system/themes/pfadi-facebook.svg: pfadi-facebook.svg, create, update, careful
system/themes/pfadi-kumbhsans.woff2: pfadi-kumbhsans.woff2, create, update, careful
system/themes/pfadi-kumbhsans-license.txt: pfadi-kumbhsans-license.txt, create
system/themes/pfadi-gloriahallelujah.woff2: pfadi-gloriahallelujah.woff2, create, update, careful
system/themes/pfadi-gloriahallelujah-license.txt: pfadi-gloriahallelujah-license.txt, create
